import 'dart:convert';

HallOfFameModels hallOfFameModelsFromJson(String str) =>
    HallOfFameModels.fromJson(json.decode(str));

String hallOfFameModelsToJson(HallOfFameModels data) =>
    json.encode(data.toJson());

class HallOfFameModels {
  final bool success;
  final String message;
  final List<HallOfFameItem> data;
  final Meta? meta;

  HallOfFameModels({
    required this.success,
    required this.message,
    required this.data,
    this.meta,
  });

  factory HallOfFameModels.fromJson(Map<String, dynamic> json) =>
      HallOfFameModels(
        success: json["success"] ?? false,
        message: json["message"] ?? "",
        data: (json["data"] as List?)
                ?.map((x) => HallOfFameItem.fromJson(x))
                .toList() ??
            [],
        meta: json["meta"] != null ? Meta.fromJson(json["meta"]) : null,
      );

  Map<String, dynamic> toJson() => {
        "success": success,
        "message": message,
        "data": data.map((x) => x.toJson()).toList(),
        "meta": meta?.toJson(),
      };
}

class HallOfFameItem {
  final String id;
  final String eventType;
  final EventId? eventId;
  final String eventModel;
  final List<Winner> winners;
  final DateTime? eventDate;
  final bool isAutoGenerated;
  final DateTime? createdAt;

  HallOfFameItem({
    required this.id,
    required this.eventType,
    this.eventId,
    required this.eventModel,
    required this.winners,
    this.eventDate,
    required this.isAutoGenerated,
    this.createdAt,
  });

  factory HallOfFameItem.fromJson(Map<String, dynamic> json) =>
      HallOfFameItem(
        id: json["_id"]?.toString() ?? "",
        eventType: json["eventType"]?.toString() ?? "",
        eventId:
            json["eventId"] != null ? EventId.fromJson(json["eventId"]) : null,
        eventModel: json["eventModel"]?.toString() ?? "",
        winners: (json["winners"] as List?)
                ?.map((x) => Winner.fromJson(x))
                .toList() ??
            [],
        eventDate: json["eventDate"] != null
            ? DateTime.tryParse(json["eventDate"])
            : null,
        isAutoGenerated: json["isAutoGenerated"] ?? false,
        createdAt: json["createdAt"] != null
            ? DateTime.tryParse(json["createdAt"])
            : null,
      );

  Map<String, dynamic> toJson() => {
        "_id": id,
        "eventType": eventType,
        "eventId": eventId?.toJson(),
        "eventModel": eventModel,
        "winners": winners.map((x) => x.toJson()).toList(),
        "eventDate": eventDate?.toIso8601String(),
        "isAutoGenerated": isAutoGenerated,
        "createdAt": createdAt?.toIso8601String(),
      };
}

class EventId {
  final String id;
  final String title;

  EventId({
    required this.id,
    required this.title,
  });

  factory EventId.fromJson(Map<String, dynamic> json) => EventId(
        id: json["_id"]?.toString() ?? "",
        title: json["title"]?.toString() ?? "",
      );

  Map<String, dynamic> toJson() => {
        "_id": id,
        "title": title,
      };
}

class Winner {
  final int position;
  final Student? student;

  // 🔥 ADD THESE
  final String studentName;
  final String profileImage;
  final String quote;

  final double score;
  final String prize;

  Winner({
    required this.position,
    this.student,

    required this.studentName,
    required this.profileImage,
    required this.quote,

    required this.score,
    required this.prize,
  });

  factory Winner.fromJson(Map<String, dynamic> json) => Winner(
        position: json["position"] ?? 0,

        student: json["student"] != null
            ? Student.fromJson(json["student"])
            : null,

        // 🔥 ADD THESE
        studentName: json["studentName"]?.toString() ?? "",
        profileImage: json["profileImage"]?.toString() ?? "",
        quote: json["quote"]?.toString() ?? "",

        score: (json["score"] as num?)?.toDouble() ?? 0.0,
        prize: json["prize"]?.toString() ?? "",
      );

  Map<String, dynamic> toJson() => {
        "position": position,
        "student": student?.toJson(),

        "studentName": studentName,
        "profileImage": profileImage,
        "quote": quote,

        "score": score,
        "prize": prize,
      };
}
class Student {
  final String id;
  final String name;
  final String email;
  final String? profileImage;

  Student({
    required this.id,
    required this.name,
    required this.email,
    this.profileImage,
  });

  factory Student.fromJson(Map<String, dynamic> json) => Student(
        id: json["_id"]?.toString() ?? "",
        name: json["name"]?.toString() ?? "",
        email: json["email"]?.toString() ?? "",
        profileImage: json["profileImage"]?.toString(),
      );

  Map<String, dynamic> toJson() => {
        "_id": id,
        "name": name,
        "email": email,
        "profileImage": profileImage,
      };
}
class Meta {
  final int page;
  final int limit;
  final int total;
  final int pages;

  Meta({
    required this.page,
    required this.limit,
    required this.total,
    required this.pages,
  });

  factory Meta.fromJson(Map<String, dynamic> json) => Meta(
        page: json["page"] ?? 1,
        limit: json["limit"] ?? 10,
        total: json["total"] ?? 0,
        pages: json["pages"] ?? 1,
      );

  Map<String, dynamic> toJson() => {
        "page": page,
        "limit": limit,
        "total": total,
        "pages": pages,
      };
}